### ISSUE TITLE
Database.getFlows() needs to get existing flows and give them to Flow/Index

### ISSUE THREAD

**Issue by Connorapple** [productivityinterns/productivitywebapp#10]

**Comment by mgallig** [comment]
@Connorapple @KaitlynND @Tclark26 @Bed3150n Siight change of plans due to technical issues with Sqlite imnplementation. Instead of having a separate bucket for Template and Flows, I added a field to Flows called IsATemplate, which is true when a flow is a template.

Sorta hacky, but fastest way to move forward.

Theres as bunch of .Include code that youll have to use on getFlows(), and I've stubbed it out in GetTemplates(), and need to feed this into the view.


I am out today! I was at work super late last night as we had something come up! See you folks tomorrow morning.

**Comment by Connorapple** [comment]
So we actually worked with that and were able to create a model containing both templates and fillable flows, then display them in the index page, we used your stubbed out code and have a working, save() getFlows(), and index page with working displays. we are currently working on delete functionality, bu t encountering problems with the routing to action.
Have fun on your day off!
